version: '3.9'

services:
  db:
    image: postgres:latest
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./DDL/scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=manpukuya
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"